/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Model.Usuario;

/**
 *
 * @author conta
 */
public class TelaGerenciarPerguntas extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form AreaAdm
     */
    public TelaGerenciarPerguntas(Usuario usuario) {
        initComponents();
        setaButton.setContentAreaFilled(false);
    setaButton.setBorderPainted(false);
    setaButton.setFocusPainted(false);
    setaButton.setOpaque(false);
    this.setLocationRelativeTo(null);
    this.setResizable(  false);  
    this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        setaButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        areaadmCadastrarButton = new javax.swing.JButton();
        editarPerguntasButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        removerPerguntasButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255, 220));

        setaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/seta1-removebg-preview.png"))); // NOI18N
        setaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1490, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(setaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 80));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 220));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 0, 36)); // NOI18N
        jLabel2.setText("Perguntas");

        areaadmCadastrarButton.setBackground(new java.awt.Color(42, 122, 195));
        areaadmCadastrarButton.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        areaadmCadastrarButton.setForeground(new java.awt.Color(255, 255, 255));
        areaadmCadastrarButton.setText("Adicionar perguntas");
        areaadmCadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaadmCadastrarButtonActionPerformed(evt);
            }
        });

        editarPerguntasButton.setBackground(new java.awt.Color(42, 122, 195));
        editarPerguntasButton.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        editarPerguntasButton.setForeground(new java.awt.Color(255, 255, 255));
        editarPerguntasButton.setText("Editar perguntas");
        editarPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerguntasButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_Poliedro_Horiz_EDUCACAO_300x70.png"))); // NOI18N

        removerPerguntasButton.setBackground(new java.awt.Color(42, 122, 195));
        removerPerguntasButton.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        removerPerguntasButton.setForeground(new java.awt.Color(255, 255, 255));
        removerPerguntasButton.setText("Remover perguntas");
        removerPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPerguntasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(areaadmCadastrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarPerguntasButton, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(removerPerguntasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel2)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(areaadmCadastrarButton)
                .addGap(50, 50, 50)
                .addComponent(removerPerguntasButton)
                .addGap(50, 50, 50)
                .addComponent(editarPerguntasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 510, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img corredor - png.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setaButtonActionPerformed
        // TODO add your handling code here:
        AreaAdm admTela = new AreaAdm(usuario);
        admTela.setVisible(true);
        dispose();

    }//GEN-LAST:event_setaButtonActionPerformed

    private void areaadmCadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaadmCadastrarButtonActionPerformed
        // TODO add your handling code here:
        TelaAdicionarPeguntas AddPerguntasTela = new TelaAdicionarPeguntas(usuario);
        AddPerguntasTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_areaadmCadastrarButtonActionPerformed

    private void removerPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPerguntasButtonActionPerformed
        // TODO add your handling code here:
        TelaRemoverPerguntas removerTela = new TelaRemoverPerguntas(usuario);
        removerTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_removerPerguntasButtonActionPerformed

    private void editarPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerguntasButtonActionPerformed
        // TODO add your handling code here:
        TelaEditarPerguntas editarPerguntasTela = new TelaEditarPerguntas(usuario);
        editarPerguntasTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_editarPerguntasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaGerenciarPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaGerenciarPerguntas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaadmCadastrarButton;
    private javax.swing.JButton editarPerguntasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removerPerguntasButton;
    private javax.swing.JButton setaButton;
    // End of variables declaration//GEN-END:variables
}
