/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Model.Alternativa;
import Model.Jogo;
import Model.Usuario;
import java.awt.Color;
import java.util.List;
import javax.swing.Timer;

/**
 *
 * @author conta
 */
public class TelaJogo1 extends javax.swing.JFrame {

    List<Alternativa> alternativas;
    Jogo jogo;
    Usuario usuario;
    Alternativa alternativa_escolhida;
    javax.swing.JToggleButton botao_clicado;

    public Usuario getUsuario() {
        return usuario;
    }

    /**
     * Creates new form TelaJogo1
     */
    public TelaJogo1(Usuario usuario) {
        initComponents();
        jPanel3.setVisible(false);
        mascoteFeliz.setVisible(false);
        mascoteTriste.setVisible(false);
        this.setVisible(true);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(false);
        jPanel3.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.jogo = new Jogo(this);
        this.usuario = usuario;
        System.out.println(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        simButton = new javax.swing.JButton();
        naoButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        mascoteTriste = new javax.swing.JLabel();
        mascote = new javax.swing.JLabel();
        mascoteFeliz = new javax.swing.JLabel();
        barraVerdeFacil = new javax.swing.JProgressBar();
        barraAmarelaMedio = new javax.swing.JProgressBar();
        barraVermelhaDificil = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Super Crumble", 0, 24)); // NOI18N
        jLabel9.setText("Está certo disso?");

        simButton.setBackground(new java.awt.Color(13, 255, 0));
        simButton.setFont(new java.awt.Font("Super Crumble", 0, 18)); // NOI18N
        simButton.setForeground(new java.awt.Color(255, 255, 255));
        simButton.setText("Sim");
        simButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simButtonActionPerformed(evt);
            }
        });

        naoButton.setBackground(new java.awt.Color(248, 17, 17));
        naoButton.setFont(new java.awt.Font("Super Crumble", 0, 18)); // NOI18N
        naoButton.setForeground(new java.awt.Color(255, 255, 255));
        naoButton.setText("Não");
        naoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(simButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(naoButton))
                    .addComponent(jLabel9))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simButton)
                    .addComponent(naoButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 100));

        jToggleButton6.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jToggleButton6.setText("ABSCDV");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jToggleButton7.setText("ASDD");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jToggleButton8.setText("ASDSD");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jToggleButton9.setText("ASDSA");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jToggleButton10.setText("SDFGHJKL");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     A");

        jLabel5.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("     B");

        jLabel6.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("    C");

        jLabel7.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("    D");

        jLabel8.setFont(new java.awt.Font("Javanese Text", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  E");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(3);
        jTextArea1.setFont(new java.awt.Font("Javanese Text", 0, 19)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(248, 250, 252));
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton8)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton9)
                    .addComponent(jLabel7))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton10)
                    .addComponent(jLabel8))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 890, 700));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Dica1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 700, 80, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Dica5.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 700, 80, 80));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/dica6.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 700, 80, 80));

        mascoteTriste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MascoteTriste.png"))); // NOI18N
        getContentPane().add(mascoteTriste, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 360, 540));

        mascote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Mascote.png"))); // NOI18N
        getContentPane().add(mascote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 380, 520));

        mascoteFeliz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MascoteFeliz-removebg-preview.png"))); // NOI18N
        getContentPane().add(mascoteFeliz, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 180, 360, 510));

        barraVerdeFacil.setForeground(new Color(57, 144, 156));
        barraVerdeFacil.setOrientation(1);
        barraVerdeFacil.setOpaque(true);
        barraVerdeFacil.setPreferredSize(new java.awt.Dimension(4, 150));
        getContentPane().add(barraVerdeFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 80, 233));

        barraAmarelaMedio.setForeground(new Color(255, 193, 7));
        barraAmarelaMedio.setOrientation(1);
        barraAmarelaMedio.setOpaque(true);
        barraAmarelaMedio.setPreferredSize(new java.awt.Dimension(4, 150));
        getContentPane().add(barraAmarelaMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 80, 233));

        barraVermelhaDificil.setForeground(new Color(244, 67, 54));
        barraVermelhaDificil.setOrientation(1);
        barraVermelhaDificil.setOpaque(true);
        barraVermelhaDificil.setPreferredSize(new java.awt.Dimension(4, 150));
        getContentPane().add(barraVermelhaDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 233));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TelaDeFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1430, 1030));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jogo.dicaRemove2();
        jButton3.setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jogo.pularQuestao();
        jButton1.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        alternativa_escolhida = alternativas.get(0);
        botao_clicado = jToggleButton6;
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
        alternativa_escolhida = alternativas.get(1);
        botao_clicado = jToggleButton7;
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        alternativa_escolhida = alternativas.get(2);
        botao_clicado = jToggleButton8;
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        alternativa_escolhida = alternativas.get(3);
        botao_clicado = jToggleButton9;
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        alternativa_escolhida = alternativas.get(4);
        botao_clicado = jToggleButton10;
        jPanel3.setVisible(true);

    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jogo.dicaUniversitarios();
        jButton2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void simButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simButtonActionPerformed
        // TODO add your handling code here:
        botao_clicado.setSelected(false);
        if (jogo.tratandoResposta(alternativa_escolhida)) {
            botao_clicado.setBackground(new Color(46, 204, 113));
            mascote.setVisible(false);
            mascoteFeliz.setVisible(true);
        } else {
            botao_clicado.setBackground(new Color(231, 76, 60));
            mascote.setVisible(false);
            mascoteTriste.setVisible(true);
        }
        botao_clicado.setOpaque(true);
        botao_clicado.setContentAreaFilled(true);
        botao_clicado.repaint();
        jPanel3.setVisible(false);
        Timer timer = new Timer(2000, e -> {
            mascoteTriste.setVisible(false);
            mascoteFeliz.setVisible(false);
            mascote.setVisible(true);
            jogo.finalizaJogo();
            jogo.gerarPergunta();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_simButtonActionPerformed

    private void naoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoButtonActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(false);
    }//GEN-LAST:event_naoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaJogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaJogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaJogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaJogo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaJogo1().setVisible(true);
//            }
//        });
//    }
    public void exibePergunta(String pergunta) {
        jTextArea1.setText(pergunta);
        jTextArea1.setEditable(false);            
        jTextArea1.setFocusable(false); 
        jTextArea1.setLineWrap(true);            
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.getViewport().setOpaque(false);
        jTextArea1.setHighlighter(null); 
        jTextArea1.enableInputMethods(false);
        jTextArea1.setDragEnabled(false);
        jTextArea1.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraAmarelaMedio;
    private javax.swing.JProgressBar barraVerdeFacil;
    private javax.swing.JProgressBar barraVermelhaDificil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel mascote;
    private javax.swing.JLabel mascoteFeliz;
    private javax.swing.JLabel mascoteTriste;
    private javax.swing.JButton naoButton;
    private javax.swing.JButton simButton;
    // End of variables declaration//GEN-END:variables

    public void atualizaBarraVerde(boolean acertou) {
        if (acertou) {
            barraVerdeFacil.setValue(barraVerdeFacil.getValue() + 25);
        } else {
            barraVerdeFacil.setValue(0);
        }
    }

    public void atualizaBarraAmarela(boolean acertou) {
        if (acertou) {
            barraAmarelaMedio.setValue(barraAmarelaMedio.getValue() + 25);
        } else {
            barraAmarelaMedio.setValue(0);
        }
    }

    public void atualizaBarraVermelha(boolean acertou) {
        if (acertou) {
            barraVermelhaDificil.setValue(barraVermelhaDificil.getValue() + 25);
        } else {
            barraVermelhaDificil.setValue(0);
        }
    }

    public void exibeAlternativas(List<Alternativa> alternativas) {
        this.alternativas = alternativas;
        jToggleButton6.setBackground(Color.WHITE);
        jToggleButton7.setBackground(Color.WHITE);
        jToggleButton8.setBackground(Color.WHITE);
        jToggleButton9.setBackground(Color.WHITE);
        jToggleButton10.setBackground(Color.WHITE);
        definirTextoBotao(jToggleButton6, 0);
        definirTextoBotao(jToggleButton7, 1);
        definirTextoBotao(jToggleButton8, 2);
        definirTextoBotao(jToggleButton9, 3);
        definirTextoBotao(jToggleButton10, 4);
    }

    private void definirTextoBotao(javax.swing.JToggleButton botao, int indice) {
        if (alternativas.get(indice) != null) {
            botao.setText(alternativas.get(indice).getTexto());
        } else {
            botao.setText("Alternativa Removida");
        }
        botao.setOpaque(true);
        botao.setContentAreaFilled(true);
        botao.repaint();
    }

}
